version: "2"
services:
  mysql:
    image: "mysql:5.7"
    volumes:
      - /usr/lib/mysql
    restart: "on-failure"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306